version: '3.4'

services:


 

  

  quantum:

 

    image: ${DOCKER_REGISTRY-}quantum
    build:
      context: Quantum
      dockerfile: Dockerfile
    ports:
      - 8002:1433
   
  dbcontainer:
    container_name: db-container
    image:  mcr.microsoft.com/mssql/server:2022-latest

    
    ports:
     - "7000:7000"
     - "7001:7001"

   